Change in value!
iteration:  2 and last- 1476773066.87
Change in value!
iteration:  7 and last- 1476773079.66
Change in value!
iteration:  8 and last- 1476776115.54
Change in value!
iteration:  10 and last- 1476776723.61
Change in value!
iteration:  13 and last- 1476777936.26
Change in value!
iteration:  14 and last- 1476779756.13
Change in value!
iteration:  17 and last- 1476780365.25
Change in value!
iteration:  22 and last- 1476782187.83
Change in value!
iteration:  23 and last- 1476785227.61
Change in value!
iteration:  25 and last- 1476785834.34
Change in value!
iteration:  26 and last- 1476787050.18
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    func()
  File "test.py", line 26, in func
    stocks=investor.getStocks()
  File "/home/caleb/investor/investor.py", line 43, in getStocks
    data = self.google.get(comp[0], comp[1])
  File "/home/caleb/investor/google.py", line 11, in get
    u = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
